[project]
name = "asyncio-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "asyncio>=4.0.0",
    "httpx>=0.28.1",
    "pillow>=12.0.0",
    "requests>=2.32.5",
    "scalene>=1.5.55",
]
